insert into T_AUTHOR(name, bio, twitter_name) values ('Craig Walls', 'Craig Walls has been professionally developing software for almost 18 years (and longer than that for the pure geekiness of it). He is a senior engineer with SpringSource as the Spring Social project lead and is the author of Spring in Action and XDoclet in Action (both published by Manning) and Modular Java (published by Pragmatic Bookshelf). He''s a zealous promoter of the Spring Framework, speaking frequently at local user groups and conferences and writing about Spring and OSGi on his blog. When he''s not slinging code, Craig spends as much time as he can with his wife, two daughters, 4 birds and 3 dogs.', 'habuma');
insert into T_AUTHOR(name, bio, twitter_name) values ('Kenneth Kousen', 'Ken Kousen is the President of Kousen IT, Inc., through which he does technical training, mentoring, and consulting in all areas of Java and XML. He is the author of the O''Reilly screencast "Up and Running Groovy", and the upcoming Manning book about Java/Groovy integration, entitled "Making Java Groovy".', 'kenkousen');
insert into T_AUTHOR(name, bio, twitter_name) values ('Kirk Knoernschild', 'Kirk is software developer with a passion for building great software. He takes a keen interest in design, architecture, application development platforms, agile development, and the IT industry in general, especially as it relates to software development. His recent book, Java Application Architecture was published in 2012, and presents 18 patterns that help you design modular software.', 'pragkirk');
insert into T_AUTHOR(name, bio, twitter_name) values ('Nathaniel Schutta', 'Nathaniel T. Schutta is a senior software engineer focussed on making usable applications. A proponent of polyglot programming, Nate has written two books on Ajax and speaks regularly at various worldwide conferences, No Fluff Just Stuff symposia, universities, and Java user groups. In addition to his day job, Nate is an adjunct professor at the University of Minnesota where he teaches students to embrace dynamic languages. In an effort to rid the world of bad presentations, Nate coauthored the book Presentation Patterns with Neal Ford and Matthew McCullough.', 'ntschutta');

insert into T_BOOK (title, author_id) values ('Spring in Action', 1);
insert into T_BOOK (title, author_id) values ('Modular Java', 1);
insert into T_BOOK (title, author_id) values ('Making Java Groovy', 2);
insert into T_BOOK (title, author_id) values ('Java Application Architecture', 3);
insert into T_BOOK (title, author_id) values ('Presentation Patterns', 4);